### ISSUE TITLE
 LaTeX Error: File `protobuf/style.sty' not found.

### ISSUE THREAD

**Issue by YimengZhu** [aytchell/latex-listings-protobuf#1]
Hi. Thanks for sharing this package.

After added the usage of this package and click the compile in texmaker I got the error:

 LaTeX Error: File `protobuf/style.sty' not found.

Do you have any suggestion about where I should place the .sty file?

Thanks

**Comment by aytchell** [comment]
Hi YimengZhu,

I'm not using Texmaker so I can't say much about this tool.

But regarding LaTeX you could try these options:
- Probably easiest: make a new subdirectory named 'protobuf' in the directory of your main tex-file. Copy the two sty-files into this subdir. Works but has to be repeated for each new document.
- Related but "a bit more hacky": Copy the sty-files in the directory of your tex-file and change usepackage{protobuf/style} and usepackage{protobuf/lang} to ...{style} and ...{lang}. (This is basically the same as the first option but will clutter your working directory.)
- In my Makefile I set the environment variable TEXINPUTS telling LaTeX where to search for sty-files; this might not be an option with texmaker. (This is kind of a poor-mans-texmf)
- or "the correct"(tm) method is to add the sty-files to your local texmf tree (see "man texhash" or "man texlsr"). In this case you should probably rename the files to something "less generic" (and also remove the 'protobuf/' part from the "usepackage"-parameter); this is the most initial work but best if you plan to use the sty a lot.

HTH,
Hannes

**Comment by YimengZhu** [comment]
Hi Hannes,
The first two solution work in my case.
Thanks for you help.!
